name: Deploy JavaScript Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh $USERNAME@$SERVER "mkdir -p ~/intern3-js-app"
        scp -r ./* $USERNAME@$SERVER:~/intern3-js-app
        ssh $USERNAME@$SERVER "cd ~/intern3-js-app && npm install --production && pm2 restart all"